name: CI/CD Pipeline Deploy to AWS ECS

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        env:
          SPRING_CONFIG_LOCATION: src/test/resources/application-test.yml
        run: mvn package --file pom.xml
      - name: Run Unit Tests
        env:
          SPRING_CONFIG_LOCATION: src/test/resources/application-test.yml
        run: mvn test --file pom.xml

  build:
    name: Build and publish on ECS
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: brewery-tour
#          DB_URL: ${{ secrets.DB_URL }}
#          DB_USER: ${{ secrets.DB_USER }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: brewery-tour-task-definition.json
          container-name: brewery-tour
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: brewery-tour-service
          cluster: DevCluster1
          wait-for-service-stability: true

  build2:
    name: Build docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: |
          docker login -u $USERNAME -p $PASSWORD
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build . -t $USERNAME/brewery-tour:$GITHUB_SHA --build-arg DB_URL=$DB_URL --build-arg DB_USER=$DB_USER --build-arg DB_PASSWORD=$DB_PASSWORD
          docker push $USERNAME/brewery-tour:$GITHUB_SHA
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

  deploy:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy with flyctl
        run: |
          flyctl deploy --remote-only -a brewery-tour --image docker.io/$USERNAME/brewery-tour:$GITHUB_SHA --env DB_URL=$DB_URL --env DB_USER=$DB_USER --env DB_PASSWORD=$DB_PASSWORD
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
