name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "master" ]
    types: [closed]

jobs:
  test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        env:
          SPRING_CONFIG_LOCATION: src/test/resources/application-test.yml
        run: mvn package --file pom.xml
      - name: Run Unit Tests
        env:
          SPRING_CONFIG_LOCATION: src/test/resources/application-test.yml
        run: mvn test --file pom.xml

  build:
    name: Build docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: |
          docker login -u $USERNAME -p $PASSWORD
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build . -t $USERNAME/brewery-tour:$GITHUB_SHA --build-arg DB_URL=$DB_URL --build-arg DB_USER=$DB_USER --build-arg DB_PASSWORD=$DB_PASSWORD
          docker push $USERNAME/brewery-tour:$GITHUB_SHA
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

  deploy:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy with flyctl
        run: flyctl deploy --remote-only -a brewery-tour --image docker.io/$USERNAME/brewery-tour:$GITHUB_SHA
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}